name: Custom User Mode CI

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker-compose build --no-cache

      - name: Run tests and upload coverage to Codecov
        run: |
          ci_env="bash <(curl -s https://codecov.io/env)"
          ci_post_cov="bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}"
          docker-compose run -e CI=true --rm api bash -c "$ci_env && pytest && $ci_post_cov"
